$axure.loadCurrentPage({
  "url":"主页.html",
  "generationDate":new Date(1393157729004.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7755e52db6fe480da89c0c7a61c88806",
    "type":"Axure:Page",
    "name":"主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e92ff393dfa545d79bce3f5999092e91",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":406,
              "y":830},
            "size":{
              "width":120,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe5bc601ad614c98b334fae0d91f8b86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":406,
                  "y":830},
                "size":{
                  "width":120,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"49d5647caeef4c6bbd635bd1ba6bdc03",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":416,
              "y":830},
            "size":{
              "width":120,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe30d4553efb4a4397af514cd0190b23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":416,
                  "y":830},
                "size":{
                  "width":120,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"3947e32c4e0c485db732a9ff1c4451ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":169.5,
              "y":750},
            "size":{
              "width":400,
              "height":400}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bf258a1dcb741d8bcf82cdff2bea88e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169.5,
                  "y":750},
                "size":{
                  "width":400,
                  "height":400}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u4.png"}},
{
          "id":"0ad4405359c141298e658bbfe7feb78e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":40},
            "size":{
              "width":400,
              "height":560}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfb539cf080041538e033a667bb34f9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":40},
                "size":{
                  "width":400,
                  "height":560}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u6.png"}},
{
          "id":"9df66b1a7b8b45359bd17e419e45b344",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":510,
              "y":40.5},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fb14bdbe1c542b386c660a0f3e7bad2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":510,
                  "y":40.5},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "Description":"添加"},
          "images":{
            "normal~":"images/主页/u8.png"}},
{
          "id":"a87d38a333484f4490bed9c8ecffeaa4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":86},
            "size":{
              "width":400,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u10_line.png"}},
{
          "id":"95f91aad99c8432ba22093a3013dbf7f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":170,
              "y":40},
            "size":{
              "width":70,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f01ed4cfb7a432e9d973618ebf9a133",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":170,
                  "y":40},
                "size":{
                  "width":70,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u11.png"}},
{
          "id":"69e5921ddf674a3ca36b7a7015da900e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":290},
            "size":{
              "width":120,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"311bab4527544bcca9a2a75d7809c5d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":290},
                "size":{
                  "width":120,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"a55639e5b86840179277a6263a5024d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":290},
            "size":{
              "width":120,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bb4ab8319704cf99567c86eb3a075bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":290},
                "size":{
                  "width":120,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u15.png"}},
{
          "id":"79ecc0df62f9488babb80a681cecee6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":200,
              "y":390},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44f3b58eef51487eb6b5c35382d332c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":200,
                  "y":390},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a24b8ceb7894b4e80f3f675265d73c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":290},
            "size":{
              "width":120,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"817123210f2d45d7ad32695280c5aba3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":290},
                "size":{
                  "width":120,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"d1ae3b0ba6564a8aa68987bbff4f4f50",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":410,
              "y":390},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f88c49562bdc42cfb665a10e58aec83d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":410,
                  "y":390},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48098744f1a342339b479c239cb8619a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":409,
              "y":290},
            "size":{
              "width":120,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f6b879d3332496082ffbffabad8f94f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":409,
                  "y":290},
                "size":{
                  "width":120,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u15.png"}},
{
          "id":"80f0b4c36a984c2d8d4267bf6de5b547",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":460},
            "size":{
              "width":120,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2c4711e1fae49068772a1d5ff018648",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":201,
                  "y":460},
                "size":{
                  "width":120,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"16526c207da447288eaaae9b6b34da1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":201,
              "y":560},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1db9b22a29c44897bd5f0e3f92d52c11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":201,
                  "y":560},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d48582d9b5ec473aa88c638a4f10d651",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":460},
            "size":{
              "width":120,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ed7a12c58fc44dd868c28c431d85b64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":201,
                  "y":460},
                "size":{
                  "width":120,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u15.png"}},
{
          "id":"c3b62033f9f34488860c8206a06dc9fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":411,
              "y":460},
            "size":{
              "width":120,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11ec04183d9d4fa4aa5446611b541de2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":411,
                  "y":460},
                "size":{
                  "width":120,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"0469e8b2ee024daeae2b574e033fef73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":411,
              "y":560},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"521d39f7f7b9458e9cb909e8bae9a322",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":411,
                  "y":560},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a68fe7b9323244cb823a6377e725a837",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":460},
            "size":{
              "width":120,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"850e80c5617d48fb8c7b4c69ce607fef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":460},
                "size":{
                  "width":120,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u15.png"}},
{
          "id":"a91b671f6010425aba3e3d360bd6be94",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":72},
            "size":{
              "width":90,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u37_line.png"}},
{
          "id":"ebb0a3a85d244812950ef42addf58761",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":620,
              "y":49},
            "size":{
              "width":110,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9487c2ca1522439ab0e5abf6018e70a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":620,
                  "y":49},
                "size":{
                  "width":110,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b91bdbd7dac2412a98a1bfe5844b1fe1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":172,
              "y":796},
            "size":{
              "width":400,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u10_line.png"}},
{
          "id":"0141868f673e42ae93e6f32a52ddbd45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":172,
              "y":750},
            "size":{
              "width":70,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cc9ff0a2e2d42868242e9e861e2704c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":172,
                  "y":750},
                "size":{
                  "width":70,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u11.png"}},
{
          "id":"4f8754b9f8794fe0a68ae2c3fa172bad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":512,
              "y":750},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf0fbf250e8e4413a3239d697cfb06c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":512,
                  "y":750},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u8.png"}},
{
          "id":"d1c4451747a740d99e0c606958ba8a26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":830},
            "size":{
              "width":120,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd5536f7cc894e2d8eb4b437c1709941",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":206,
                  "y":830},
                "size":{
                  "width":120,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"57e6e47b1d1a49fdbd581b5d66826f30",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":830},
            "size":{
              "width":120,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c6f0454c28e435ea0201f7a9979e77e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":206,
                  "y":830},
                "size":{
                  "width":120,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u15.png"}},
{
          "id":"2820387bd9594c8f968227b159c2d625",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":206,
              "y":930},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94d1dbf7dcfc44c282275ebe60b9c624",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":206,
                  "y":930},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c21ae66b7b634e2681e4e66d5ca26542",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":1000},
            "size":{
              "width":120,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c06ee446a174aeb9c1ceb447b9588da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":1000},
                "size":{
                  "width":120,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"fecf3f276b2549f48747af7b752c00d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":1000},
            "size":{
              "width":120,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1be51c8125ed4846b27ad76c4c085838",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":1000},
                "size":{
                  "width":120,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"afd1cb2466474d82a8f2f5ba90a9ae10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":208,
              "y":1100},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb78e1f372f1426a93a32b769c87ddb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":208,
                  "y":1100},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e94f855ece3145d6bb325ba287015229",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":1000},
            "size":{
              "width":120,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"702f7acca5bc407283b1638c6a2a3085",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":206,
                  "y":1000},
                "size":{
                  "width":120,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u15.png"}},
{
          "id":"85e4700919b24d9bac0b6e253df1d50c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":418,
              "y":1100},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"110b8cb8ca9e47b8b0e821e45380c38f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":418,
                  "y":1100},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e4dc4f66d164d0888c0b2f48b1c5a4b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":411,
              "y":1000},
            "size":{
              "width":120,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee72f10a06f54835a197f0798bcc8d48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":411,
                  "y":1000},
                "size":{
                  "width":120,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u15.png"}},
{
          "id":"93e6b676afad4563986bca257f85e598",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":782},
            "size":{
              "width":118,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u63_line.png"}},
{
          "id":"c728cab504fc455596a09942bcf16907",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":620,
              "y":750},
            "size":{
              "width":110,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e010edfec86d4325a38ef80b2daf732f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":620,
                  "y":750},
                "size":{
                  "width":110,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8396fb6d6cd24ee984c706f82a500b61",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":406,
              "y":830},
            "size":{
              "width":120,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f39a4ea64ed34d77affaba6df910890b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":406,
                  "y":830},
                "size":{
                  "width":120,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"845e3f05e7c04ae0889a2e4d0caa04f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":406,
              "y":830},
            "size":{
              "width":120,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2168b5cf78a144b1aaeeda394d4be7b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":406,
                  "y":830},
                "size":{
                  "width":120,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u15.png"}},
{
          "id":"8b6d5319fff2478bb7f1b6e7b23d352d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":406,
              "y":930},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd4e1cae2bcd4313bb40b940e6bc5e83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":406,
                  "y":930},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60466d3fd9cc4c238a5332dbde3c697d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":106},
            "size":{
              "width":323,
              "height":154}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55b39eee27c140cd92cfe08a56c9b466",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":106},
                "size":{
                  "width":323,
                  "height":154}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u72.png"}},
{
          "id":"8998980ad99442fd9abcf0b1f31e5eb5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":106},
            "size":{
              "width":113,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c6151d0d7174e7aaa9db836c2a78d6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":106},
                "size":{
                  "width":113,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u74.png"}},
{
          "id":"df9d99dd51be4ef99750fbe8791bbe95",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":321,
              "y":106},
            "size":{
              "width":113,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6f18d1c54714e66b8b4a7f218e558bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":321,
                  "y":106},
                "size":{
                  "width":113,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u74.png"}},
{
          "id":"dcc873372a2042d1bad1da1cf3027137",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":106},
            "size":{
              "width":113,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"961b862cfa6a44c8a1aaf2ce67280259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":418,
                  "y":106},
                "size":{
                  "width":113,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u74.png"}},
{
          "id":"679a17430ade4c6fad4e36d4ecfe721e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":332.5,
              "y":230},
            "size":{
              "width":75,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9bec3504311462892f3655fa7a2be54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":332.5,
                  "y":230},
                "size":{
                  "width":75,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u80.png"}},
{
          "id":"87e1a60d7bf644028de668c79d261a6e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":230},
            "size":{
              "width":110,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u82_line.png"}},
{
          "id":"9c494a85ffed4e91a3e5f99bff7883e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":220},
            "size":{
              "width":92,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a9b60dc07214946a57f5e4106e403a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":220},
                "size":{
                  "width":92,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1941da030c74dd68e69efcf0dbeed1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":10},
            "size":{
              "width":106,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35836a872d9a4f9ab8a93c0e9303e3c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":68,
                  "y":10},
                "size":{
                  "width":106,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e87e1815e27a4aeb9332e5fa4209dda6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":400},
            "size":{
              "width":100,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u87_line.png"}},
{
          "id":"3f9802ab7eab496eabefd8d173a08a40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":380},
            "size":{
              "width":131,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a0ae706ddb14b0984d559195abaf99c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":380},
                "size":{
                  "width":131,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e92ff393dfa545d79bce3f5999092e91":{
      "scriptId":"u0"},
    "fe5bc601ad614c98b334fae0d91f8b86":{
      "scriptId":"u1"},
    "49d5647caeef4c6bbd635bd1ba6bdc03":{
      "scriptId":"u2"},
    "fe30d4553efb4a4397af514cd0190b23":{
      "scriptId":"u3"},
    "3947e32c4e0c485db732a9ff1c4451ef":{
      "scriptId":"u4"},
    "5bf258a1dcb741d8bcf82cdff2bea88e":{
      "scriptId":"u5"},
    "0ad4405359c141298e658bbfe7feb78e":{
      "scriptId":"u6"},
    "dfb539cf080041538e033a667bb34f9d":{
      "scriptId":"u7"},
    "9df66b1a7b8b45359bd17e419e45b344":{
      "scriptId":"u8"},
    "6fb14bdbe1c542b386c660a0f3e7bad2":{
      "scriptId":"u9"},
    "a87d38a333484f4490bed9c8ecffeaa4":{
      "scriptId":"u10"},
    "95f91aad99c8432ba22093a3013dbf7f":{
      "scriptId":"u11"},
    "1f01ed4cfb7a432e9d973618ebf9a133":{
      "scriptId":"u12"},
    "69e5921ddf674a3ca36b7a7015da900e":{
      "scriptId":"u13"},
    "311bab4527544bcca9a2a75d7809c5d1":{
      "scriptId":"u14"},
    "a55639e5b86840179277a6263a5024d4":{
      "scriptId":"u15"},
    "8bb4ab8319704cf99567c86eb3a075bc":{
      "scriptId":"u16"},
    "79ecc0df62f9488babb80a681cecee6c":{
      "scriptId":"u17"},
    "44f3b58eef51487eb6b5c35382d332c2":{
      "scriptId":"u18"},
    "3a24b8ceb7894b4e80f3f675265d73c1":{
      "scriptId":"u19"},
    "817123210f2d45d7ad32695280c5aba3":{
      "scriptId":"u20"},
    "d1ae3b0ba6564a8aa68987bbff4f4f50":{
      "scriptId":"u21"},
    "f88c49562bdc42cfb665a10e58aec83d":{
      "scriptId":"u22"},
    "48098744f1a342339b479c239cb8619a":{
      "scriptId":"u23"},
    "6f6b879d3332496082ffbffabad8f94f":{
      "scriptId":"u24"},
    "80f0b4c36a984c2d8d4267bf6de5b547":{
      "scriptId":"u25"},
    "b2c4711e1fae49068772a1d5ff018648":{
      "scriptId":"u26"},
    "16526c207da447288eaaae9b6b34da1f":{
      "scriptId":"u27"},
    "1db9b22a29c44897bd5f0e3f92d52c11":{
      "scriptId":"u28"},
    "d48582d9b5ec473aa88c638a4f10d651":{
      "scriptId":"u29"},
    "3ed7a12c58fc44dd868c28c431d85b64":{
      "scriptId":"u30"},
    "c3b62033f9f34488860c8206a06dc9fb":{
      "scriptId":"u31"},
    "11ec04183d9d4fa4aa5446611b541de2":{
      "scriptId":"u32"},
    "0469e8b2ee024daeae2b574e033fef73":{
      "scriptId":"u33"},
    "521d39f7f7b9458e9cb909e8bae9a322":{
      "scriptId":"u34"},
    "a68fe7b9323244cb823a6377e725a837":{
      "scriptId":"u35"},
    "850e80c5617d48fb8c7b4c69ce607fef":{
      "scriptId":"u36"},
    "a91b671f6010425aba3e3d360bd6be94":{
      "scriptId":"u37"},
    "ebb0a3a85d244812950ef42addf58761":{
      "scriptId":"u38"},
    "9487c2ca1522439ab0e5abf6018e70a6":{
      "scriptId":"u39"},
    "b91bdbd7dac2412a98a1bfe5844b1fe1":{
      "scriptId":"u40"},
    "0141868f673e42ae93e6f32a52ddbd45":{
      "scriptId":"u41"},
    "3cc9ff0a2e2d42868242e9e861e2704c":{
      "scriptId":"u42"},
    "4f8754b9f8794fe0a68ae2c3fa172bad":{
      "scriptId":"u43"},
    "cf0fbf250e8e4413a3239d697cfb06c8":{
      "scriptId":"u44"},
    "d1c4451747a740d99e0c606958ba8a26":{
      "scriptId":"u45"},
    "dd5536f7cc894e2d8eb4b437c1709941":{
      "scriptId":"u46"},
    "57e6e47b1d1a49fdbd581b5d66826f30":{
      "scriptId":"u47"},
    "2c6f0454c28e435ea0201f7a9979e77e":{
      "scriptId":"u48"},
    "2820387bd9594c8f968227b159c2d625":{
      "scriptId":"u49"},
    "94d1dbf7dcfc44c282275ebe60b9c624":{
      "scriptId":"u50"},
    "c21ae66b7b634e2681e4e66d5ca26542":{
      "scriptId":"u51"},
    "3c06ee446a174aeb9c1ceb447b9588da":{
      "scriptId":"u52"},
    "fecf3f276b2549f48747af7b752c00d4":{
      "scriptId":"u53"},
    "1be51c8125ed4846b27ad76c4c085838":{
      "scriptId":"u54"},
    "afd1cb2466474d82a8f2f5ba90a9ae10":{
      "scriptId":"u55"},
    "cb78e1f372f1426a93a32b769c87ddb4":{
      "scriptId":"u56"},
    "e94f855ece3145d6bb325ba287015229":{
      "scriptId":"u57"},
    "702f7acca5bc407283b1638c6a2a3085":{
      "scriptId":"u58"},
    "85e4700919b24d9bac0b6e253df1d50c":{
      "scriptId":"u59"},
    "110b8cb8ca9e47b8b0e821e45380c38f":{
      "scriptId":"u60"},
    "5e4dc4f66d164d0888c0b2f48b1c5a4b":{
      "scriptId":"u61"},
    "ee72f10a06f54835a197f0798bcc8d48":{
      "scriptId":"u62"},
    "93e6b676afad4563986bca257f85e598":{
      "scriptId":"u63"},
    "c728cab504fc455596a09942bcf16907":{
      "scriptId":"u64"},
    "e010edfec86d4325a38ef80b2daf732f":{
      "scriptId":"u65"},
    "8396fb6d6cd24ee984c706f82a500b61":{
      "scriptId":"u66"},
    "f39a4ea64ed34d77affaba6df910890b":{
      "scriptId":"u67"},
    "845e3f05e7c04ae0889a2e4d0caa04f8":{
      "scriptId":"u68"},
    "2168b5cf78a144b1aaeeda394d4be7b4":{
      "scriptId":"u69"},
    "8b6d5319fff2478bb7f1b6e7b23d352d":{
      "scriptId":"u70"},
    "cd4e1cae2bcd4313bb40b940e6bc5e83":{
      "scriptId":"u71"},
    "60466d3fd9cc4c238a5332dbde3c697d":{
      "scriptId":"u72"},
    "55b39eee27c140cd92cfe08a56c9b466":{
      "scriptId":"u73"},
    "8998980ad99442fd9abcf0b1f31e5eb5":{
      "scriptId":"u74"},
    "7c6151d0d7174e7aaa9db836c2a78d6b":{
      "scriptId":"u75"},
    "df9d99dd51be4ef99750fbe8791bbe95":{
      "scriptId":"u76"},
    "e6f18d1c54714e66b8b4a7f218e558bc":{
      "scriptId":"u77"},
    "dcc873372a2042d1bad1da1cf3027137":{
      "scriptId":"u78"},
    "961b862cfa6a44c8a1aaf2ce67280259":{
      "scriptId":"u79"},
    "679a17430ade4c6fad4e36d4ecfe721e":{
      "scriptId":"u80"},
    "a9bec3504311462892f3655fa7a2be54":{
      "scriptId":"u81"},
    "87e1a60d7bf644028de668c79d261a6e":{
      "scriptId":"u82"},
    "9c494a85ffed4e91a3e5f99bff7883e1":{
      "scriptId":"u83"},
    "1a9b60dc07214946a57f5e4106e403a8":{
      "scriptId":"u84"},
    "f1941da030c74dd68e69efcf0dbeed1c":{
      "scriptId":"u85"},
    "35836a872d9a4f9ab8a93c0e9303e3c0":{
      "scriptId":"u86"},
    "e87e1815e27a4aeb9332e5fa4209dda6":{
      "scriptId":"u87"},
    "3f9802ab7eab496eabefd8d173a08a40":{
      "scriptId":"u88"},
    "0a0ae706ddb14b0984d559195abaf99c":{
      "scriptId":"u89"}}});