$axure.loadCurrentPage({
  "url":"图片墙.html",
  "generationDate":new Date(1393157729237.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e4395717646f40d8a42e5ddab0f5dabd",
    "type":"Axure:Page",
    "name":"图片墙",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fc3d991689374133bb6ae08c7cd18614",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":40},
            "size":{
              "width":400,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c057f590a401418ab67094c645b9ea6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":40},
                "size":{
                  "width":400,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图片墙/u0.png"}},
{
          "id":"b7f8c4c9fe1e43c5a8b2ca712a3a1180",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":86},
            "size":{
              "width":400,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u10_line.png"}},
{
          "id":"0777ae2dfd154fb19892c8808eb43e39",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":170,
              "y":40},
            "size":{
              "width":70,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b250099df174d42b8d8e891e52a6fcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":170,
                  "y":40},
                "size":{
                  "width":70,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u11.png"}},
{
          "id":"3282d37f2cf749fda36fe5440df9b810",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":510,
              "y":40},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bda13b06263f4c389ec3a3015d800c5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":510,
                  "y":40},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u8.png"}},
{
          "id":"b8a777b3a89f447f8eee16986c97a3f3",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":96},
            "size":{
              "width":400,
              "height":401}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6dc2c4fe73d4374924fcd85409b1fd4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":133,
                  "height":138}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cd8243b6f278423997c37684cc13959c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":133,
                      "height":138}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/图片墙/u8.png"}},
{
              "id":"836891d6494049bbb88a25a6bd27c8be",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":138},
                "size":{
                  "width":133,
                  "height":119}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"44d7a77800d34daa9a7f68618fcd6348",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":138},
                    "size":{
                      "width":133,
                      "height":119}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/图片墙/u14.png"}},
{
              "id":"f626fbec701c46ca83e2aff95bed049f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":257},
                "size":{
                  "width":133,
                  "height":144}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f7340c76dafd4ad8955fe17e80cd3db6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":257},
                    "size":{
                      "width":133,
                      "height":144}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/图片墙/u20.png"}},
{
              "id":"dc5a8bf9cb7541f2a93656e96adf41fd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":133,
                  "y":0},
                "size":{
                  "width":133,
                  "height":138}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0a809cce95f9485baed008e636638ad4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":133,
                      "y":0},
                    "size":{
                      "width":133,
                      "height":138}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/图片墙/u8.png"}},
{
              "id":"e3456f81c3bf497a9e01bdf9eeba6dc6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":133,
                  "y":138},
                "size":{
                  "width":133,
                  "height":119}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6bc7d3df19bb41659c26c1d264c80202",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":133,
                      "y":138},
                    "size":{
                      "width":133,
                      "height":119}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/图片墙/u14.png"}},
{
              "id":"76f619e4c6c2422289c8a6788faf1f1c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":133,
                  "y":257},
                "size":{
                  "width":133,
                  "height":144}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"13c348e80ce4459ebd91612be2b839fa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":133,
                      "y":257},
                    "size":{
                      "width":133,
                      "height":144}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/图片墙/u20.png"}},
{
              "id":"8b5d9e5fbabc4befb23b0a52b4c34900",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":266,
                  "y":0},
                "size":{
                  "width":134,
                  "height":138}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e284119e65b8414d8533b0a42c41bdc1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":266,
                      "y":0},
                    "size":{
                      "width":134,
                      "height":138}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/图片墙/u12.png"}},
{
              "id":"9148c6e6fd54437b97cd5b59b107d3d3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":266,
                  "y":138},
                "size":{
                  "width":134,
                  "height":119}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"573c1436d25441da988fa5834ae9b5da",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":266,
                      "y":138},
                    "size":{
                      "width":134,
                      "height":119}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/图片墙/u18.png"}},
{
              "id":"39eb356c351d4e2198eb53d795a1404e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":266,
                  "y":257},
                "size":{
                  "width":134,
                  "height":144}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"791c02c08a3d49e6889672cf87bbf8f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":266,
                      "y":257},
                    "size":{
                      "width":134,
                      "height":144}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/图片墙/u24.png"}}]},
{
          "id":"652649271a0e437e856ae9bb30c97d35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":120},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2389d3685a314aa5a00e87d29f0ba54a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":120},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图片墙/u26.png"}},
{
          "id":"90ee3f748129469c8dd1770e90e2133a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":120},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f76b759cbb6945d9a8a63569cf64cb22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":120},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图片墙/u26.png"}},
{
          "id":"cd7fb61371a0458d8d6c7e87ee49c275",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":251.5},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7897a32ad81426fbc3459c6d73b1064",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":251.5},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图片墙/u26.png"}},
{
          "id":"264c7bdad2ea4dcd86744d079bc469d8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":120},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd8fe6a7d9ae4706acd123e6c7dfa32d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":120},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图片墙/u26.png"}},
{
          "id":"a1cda4f4e2ec436fb27a517d8fd7bddd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":251.5},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"015a5c10fc1743568bdd5c549276cc25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":251.5},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图片墙/u26.png"}},
{
          "id":"dacd4d955c5147d8b97a63936f30a7f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":252},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f794aa6c6ae4c9ea37ad90504b0834a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":252},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图片墙/u26.png"}},
{
          "id":"8d66bd2a0c444991b2ac328fe665e449",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":200},
            "size":{
              "width":120,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/图片墙/u38_line.png"}},
{
          "id":"4f916db07d37482495d358aa959b9e0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":630,
              "y":198},
            "size":{
              "width":105,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1f7c90191c045dd87231c3519a2a6a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":630,
                  "y":198},
                "size":{
                  "width":105,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b9fb0d9c1314bf8b23ca54378a6e6d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":58},
            "size":{
              "width":96,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f305d105cfa646b79f6e2f4f989ff917",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":58},
                "size":{
                  "width":96,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "fc3d991689374133bb6ae08c7cd18614":{
      "scriptId":"u0"},
    "c057f590a401418ab67094c645b9ea6e":{
      "scriptId":"u1"},
    "b7f8c4c9fe1e43c5a8b2ca712a3a1180":{
      "scriptId":"u2"},
    "0777ae2dfd154fb19892c8808eb43e39":{
      "scriptId":"u3"},
    "4b250099df174d42b8d8e891e52a6fcb":{
      "scriptId":"u4"},
    "3282d37f2cf749fda36fe5440df9b810":{
      "scriptId":"u5"},
    "bda13b06263f4c389ec3a3015d800c5c":{
      "scriptId":"u6"},
    "b8a777b3a89f447f8eee16986c97a3f3":{
      "scriptId":"u7"},
    "e6dc2c4fe73d4374924fcd85409b1fd4":{
      "scriptId":"u8"},
    "cd8243b6f278423997c37684cc13959c":{
      "scriptId":"u9"},
    "dc5a8bf9cb7541f2a93656e96adf41fd":{
      "scriptId":"u10"},
    "0a809cce95f9485baed008e636638ad4":{
      "scriptId":"u11"},
    "8b5d9e5fbabc4befb23b0a52b4c34900":{
      "scriptId":"u12"},
    "e284119e65b8414d8533b0a42c41bdc1":{
      "scriptId":"u13"},
    "836891d6494049bbb88a25a6bd27c8be":{
      "scriptId":"u14"},
    "44d7a77800d34daa9a7f68618fcd6348":{
      "scriptId":"u15"},
    "e3456f81c3bf497a9e01bdf9eeba6dc6":{
      "scriptId":"u16"},
    "6bc7d3df19bb41659c26c1d264c80202":{
      "scriptId":"u17"},
    "9148c6e6fd54437b97cd5b59b107d3d3":{
      "scriptId":"u18"},
    "573c1436d25441da988fa5834ae9b5da":{
      "scriptId":"u19"},
    "f626fbec701c46ca83e2aff95bed049f":{
      "scriptId":"u20"},
    "f7340c76dafd4ad8955fe17e80cd3db6":{
      "scriptId":"u21"},
    "76f619e4c6c2422289c8a6788faf1f1c":{
      "scriptId":"u22"},
    "13c348e80ce4459ebd91612be2b839fa":{
      "scriptId":"u23"},
    "39eb356c351d4e2198eb53d795a1404e":{
      "scriptId":"u24"},
    "791c02c08a3d49e6889672cf87bbf8f7":{
      "scriptId":"u25"},
    "652649271a0e437e856ae9bb30c97d35":{
      "scriptId":"u26"},
    "2389d3685a314aa5a00e87d29f0ba54a":{
      "scriptId":"u27"},
    "90ee3f748129469c8dd1770e90e2133a":{
      "scriptId":"u28"},
    "f76b759cbb6945d9a8a63569cf64cb22":{
      "scriptId":"u29"},
    "cd7fb61371a0458d8d6c7e87ee49c275":{
      "scriptId":"u30"},
    "b7897a32ad81426fbc3459c6d73b1064":{
      "scriptId":"u31"},
    "264c7bdad2ea4dcd86744d079bc469d8":{
      "scriptId":"u32"},
    "cd8fe6a7d9ae4706acd123e6c7dfa32d":{
      "scriptId":"u33"},
    "a1cda4f4e2ec436fb27a517d8fd7bddd":{
      "scriptId":"u34"},
    "015a5c10fc1743568bdd5c549276cc25":{
      "scriptId":"u35"},
    "dacd4d955c5147d8b97a63936f30a7f2":{
      "scriptId":"u36"},
    "2f794aa6c6ae4c9ea37ad90504b0834a":{
      "scriptId":"u37"},
    "8d66bd2a0c444991b2ac328fe665e449":{
      "scriptId":"u38"},
    "4f916db07d37482495d358aa959b9e0a":{
      "scriptId":"u39"},
    "c1f7c90191c045dd87231c3519a2a6a5":{
      "scriptId":"u40"},
    "4b9fb0d9c1314bf8b23ca54378a6e6d6":{
      "scriptId":"u41"},
    "f305d105cfa646b79f6e2f4f989ff917":{
      "scriptId":"u42"}}});