$axure.loadCurrentPage({
  "url":"大图展示.html",
  "generationDate":new Date(1393157729434.79),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"28bb0f8d4f8145eb98118d32a3b0efb0",
    "type":"Axure:Page",
    "name":"大图展示",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7b635f9f81c34bbe94ce560016d1d3f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":640},
            "size":{
              "width":400,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d6a8eb2c31f424e9423a7cdc3b81664",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":640},
                "size":{
                  "width":400,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图片墙/u0.png"}},
{
          "id":"57adceb75c244532a36168048449e178",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":686},
            "size":{
              "width":400,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u10_line.png"}},
{
          "id":"e17fbbd7fc7640fd8a7a0245e527c3ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":180,
              "y":640},
            "size":{
              "width":70,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3421b7b84b9f482b9d990eff10acce27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":180,
                  "y":640},
                "size":{
                  "width":70,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u11.png"}},
{
          "id":"7b4625f1675c42b79492910b9f867331",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":520,
              "y":640},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a28f283276241c89b4c8ff62bdeb3b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":520,
                  "y":640},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u8.png"}},
{
          "id":"31d4194fb4e44a54ae50ba10997f8225",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":710},
            "size":{
              "width":340,
              "height":380}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"312ca2d9a13f4a19847ee75a93b6b2ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":710},
                "size":{
                  "width":340,
                  "height":380}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/大图展示/u7.png"}},
{
          "id":"83b1ea47e14b475ea6832a10951f1881",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":61},
            "size":{
              "width":400,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cb5b878d87d461b82aebe1b69283707",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":61},
                "size":{
                  "width":400,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/图片墙/u0.png"}},
{
          "id":"a37785bb2d47449cb42fa2ddfe25a005",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":107},
            "size":{
              "width":400,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u10_line.png"}},
{
          "id":"2ee281d521404f76aebed4a762bf2274",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":180,
              "y":61},
            "size":{
              "width":70,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e899f289b4c496c9add0bfa1f7e1fe4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":180,
                  "y":61},
                "size":{
                  "width":70,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u11.png"}},
{
          "id":"13a73f425ab94c8395c3f355e9a83e0d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":520,
              "y":61},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"510c196558b74924b57c9dd4acddcc73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":520,
                  "y":61},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u8.png"}},
{
          "id":"2e84e8e689ac49ad810c493450d14d54",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":131},
            "size":{
              "width":340,
              "height":380}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be5db0b2834d457a878ca53a3062e936",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":131},
                "size":{
                  "width":340,
                  "height":380}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/大图展示/u7.png"}},
{
          "id":"46d8f7c5f3014562ab39a1e5222e0b9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":780},
            "size":{
              "width":170,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04acb3663890478e9ff48351b8e11e4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":780},
                "size":{
                  "width":170,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/大图展示/u18.png"}},
{
          "id":"9d209653a6ec4fd182fc13417572d225",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":295,
              "y":780},
            "size":{
              "width":170,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d914bc86f3ab49d19e2cb424f5ffcbd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":295,
                  "y":780},
                "size":{
                  "width":170,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/大图展示/u20.png"}},
{
          "id":"8b58b166332544d083e035ed65d64d6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":295,
              "y":820},
            "size":{
              "width":170,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b270cffe5aaf4814a0da48c52836086b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":295,
                  "y":820},
                "size":{
                  "width":170,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/大图展示/u20.png"}},
{
          "id":"c54c91b5f40443a0a73ebe82e9486283",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":295,
              "y":860},
            "size":{
              "width":170,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ea2b09b975f4193a33445ed602edd6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":295,
                  "y":860},
                "size":{
                  "width":170,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/大图展示/u20.png"}},
{
          "id":"e74f81a2ab294094992dedc6bd937a7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":295,
              "y":900},
            "size":{
              "width":170,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db2b8031b7d24b9696e653af3ceb5747",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":295,
                  "y":900},
                "size":{
                  "width":170,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/大图展示/u20.png"}},
{
          "id":"8882e7a7da8e4c7598b5c21673eaba24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":295,
              "y":940},
            "size":{
              "width":170,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c66c7e6962744d0af61c1273793e803",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":295,
                  "y":940},
                "size":{
                  "width":170,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/大图展示/u20.png"}},
{
          "id":"5a14ced38ad64c9281fb3c07fdd0259f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":835},
            "size":{
              "width":155,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/大图展示/u30_line.png"}},
{
          "id":"4c8b31737e5c4e84b1df5a208f1143e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":826},
            "size":{
              "width":105,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cae3123b1d7d49b091baa82f51be798d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":826},
                "size":{
                  "width":105,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8170e80aaba0404fb824ef82ac836588",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":250},
            "size":{
              "width":190,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/大图展示/u33_line.png"}},
{
          "id":"893831d90c7849fbb1750d2b1b8a353a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":245},
            "size":{
              "width":142,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76fd8c5985c44bb8885711c9e4334fbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":245},
                "size":{
                  "width":142,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7b635f9f81c34bbe94ce560016d1d3f9":{
      "scriptId":"u0"},
    "7d6a8eb2c31f424e9423a7cdc3b81664":{
      "scriptId":"u1"},
    "57adceb75c244532a36168048449e178":{
      "scriptId":"u2"},
    "e17fbbd7fc7640fd8a7a0245e527c3ef":{
      "scriptId":"u3"},
    "3421b7b84b9f482b9d990eff10acce27":{
      "scriptId":"u4"},
    "7b4625f1675c42b79492910b9f867331":{
      "scriptId":"u5"},
    "9a28f283276241c89b4c8ff62bdeb3b0":{
      "scriptId":"u6"},
    "31d4194fb4e44a54ae50ba10997f8225":{
      "scriptId":"u7"},
    "312ca2d9a13f4a19847ee75a93b6b2ca":{
      "scriptId":"u8"},
    "83b1ea47e14b475ea6832a10951f1881":{
      "scriptId":"u9"},
    "1cb5b878d87d461b82aebe1b69283707":{
      "scriptId":"u10"},
    "a37785bb2d47449cb42fa2ddfe25a005":{
      "scriptId":"u11"},
    "2ee281d521404f76aebed4a762bf2274":{
      "scriptId":"u12"},
    "0e899f289b4c496c9add0bfa1f7e1fe4":{
      "scriptId":"u13"},
    "13a73f425ab94c8395c3f355e9a83e0d":{
      "scriptId":"u14"},
    "510c196558b74924b57c9dd4acddcc73":{
      "scriptId":"u15"},
    "2e84e8e689ac49ad810c493450d14d54":{
      "scriptId":"u16"},
    "be5db0b2834d457a878ca53a3062e936":{
      "scriptId":"u17"},
    "46d8f7c5f3014562ab39a1e5222e0b9e":{
      "scriptId":"u18"},
    "04acb3663890478e9ff48351b8e11e4e":{
      "scriptId":"u19"},
    "9d209653a6ec4fd182fc13417572d225":{
      "scriptId":"u20"},
    "d914bc86f3ab49d19e2cb424f5ffcbd5":{
      "scriptId":"u21"},
    "8b58b166332544d083e035ed65d64d6b":{
      "scriptId":"u22"},
    "b270cffe5aaf4814a0da48c52836086b":{
      "scriptId":"u23"},
    "c54c91b5f40443a0a73ebe82e9486283":{
      "scriptId":"u24"},
    "9ea2b09b975f4193a33445ed602edd6f":{
      "scriptId":"u25"},
    "e74f81a2ab294094992dedc6bd937a7b":{
      "scriptId":"u26"},
    "db2b8031b7d24b9696e653af3ceb5747":{
      "scriptId":"u27"},
    "8882e7a7da8e4c7598b5c21673eaba24":{
      "scriptId":"u28"},
    "9c66c7e6962744d0af61c1273793e803":{
      "scriptId":"u29"},
    "5a14ced38ad64c9281fb3c07fdd0259f":{
      "scriptId":"u30"},
    "4c8b31737e5c4e84b1df5a208f1143e7":{
      "scriptId":"u31"},
    "cae3123b1d7d49b091baa82f51be798d":{
      "scriptId":"u32"},
    "8170e80aaba0404fb824ef82ac836588":{
      "scriptId":"u33"},
    "893831d90c7849fbb1750d2b1b8a353a":{
      "scriptId":"u34"},
    "76fd8c5985c44bb8885711c9e4334fbc":{
      "scriptId":"u35"}}});